import {authRoles} from '../../app/auth';

const navigationConfig = [
    {
        'id'   : 'applications',
        'title': 'Applications',
        'type' : 'group',
        'icon' : 'apps',
        'exact': true,
        'auth' : authRoles.admin,
        'children': [
            {
                'id'   : 'dashboard',
                'title': 'Dashboard',
                'key'  : 'Dashboard',
                'type' : 'item',
                'icon' : 'settings',
                'exact': true,
                'url'  : '/apps/dashboards/analytics',
                'auth' : authRoles.user
            },
            {
                'id'   : 'accounts',
                'title': 'Customers Account',
                'key'  : 'User',
                'type' : 'item',
                'icon' : 'account_circle',
                'url'  : '/users/accounts',
                'exact': true,
                'auth' : authRoles.user
            },
            {
                'id'   : 'chat',
                'title': 'Chat',
                'key'  : 'Chat',
                'type' : 'item',
                'icon' : 'chat',
                'url'  : '/apps/chat',
                'exact': true,
                'auth' : authRoles.user
            },
            {
                'id'   : 'transfer-queue',
                'title': 'Transfer Queue',
                'key'  : 'Transfer Queue',
                'type' : 'item',
                'icon' : 'assignment',
                'url'  : '/transfer/queue',
                'exact': true,
                'auth' : authRoles.admin
            },
            {
                'id'   : 'gl-transfer-log',
                'title': 'GL Transfer Log',
                'key'  : 'GL Transfer Log',
                'type' : 'item',
                'icon' : 'assignment',
                'url'  : '/transfer/logs',
                'exact': true,
                'auth' : authRoles.admin
            },
            {
                'id'   : 'tickets',
                'title': 'Tickets',
                'key'  : 'Tickets',
                'type' : 'collapse',
                'icon' : 'assignment',
                'url'  : '/apps/ticket',
                'exact': true,
                'auth' : authRoles.admin,
                'children': [
                    {
                        'id': 'tickets-dashboard',
                        'title': 'Tickets Dashboard',
                        'key'  : 'Tickets',
                        'type': 'item',
                        'icon': 'dashboard',
                        'url': '/apps/dashboard/tickets',
                    },
                    {
                        'id': 'tickets-list',
                        'title': 'All Tickets',
                        'key'  : 'Tickets',
                        'type': 'item',
                        'icon': 'view_list',
                        'url': '/apps/tickets',
                    },
                    {
                        'id': 'tat-response-reports',
                        'title': 'Turning Around Time',
                        'key'  : 'Tickets',
                        'type': 'item',
                        'icon': 'live_help',
                        'url': '/apps/turn-around-time'
                    }
                ],
            },
            {
                'id'   : 'investment-products-tbills',
                'title': 'Online Treasury Bills',
                'key'  : 'Treasury Bills',
                'type' : 'item',
                'url'  : '/tbills/products',
                'icon' : 'description',
                'exact': true,
                'auth' : authRoles.admin
            },
            {
                'id'   : 'investment-products-bonds',
                'title': 'Online Bonds',
                'key'  : 'Bonds',
                'type' : 'item',
                'url'  : '/bonds/products',
                'icon' : 'money',
                'exact': true,
                'auth' : authRoles.admin
            },
            {
                'id'   : 'pending-product',
                'title': 'Products Maker',
                'key'  : 'Products',
                'type' : 'item',
                'url'  : '/investment/products',
                'icon' : 'money',
                'exact': true,
                'auth' : authRoles.admin
            },
            {
                'id'   : 'maker-checker',
                'title': 'Products Checker',
                'key'  : 'Products',
                'type' : 'item',
                'icon' : 'check',
                'url'  : '/maker/checker',
                'auth' : authRoles.admin
            },
            {
                'id'   : 'deposits-maker-checker',
                'title': 'Fixed Deposit Maker/Checker',
                'key'  : 'Fixed Deposit',
                'type' : 'item',
                'icon' : 'check',
                'url'  : '/makerchecker/fixeddeposits',
                'auth' : authRoles.admin
            },
            {
                'id'   : 'fxrates-maker-checker',
                'title': 'FX Rates Maker/Checker',
                'key'  : 'FX Rate',
                'type' : 'item',
                'icon' : 'check',
                'url'  : '/makerchecker/fxrates',
                'auth' : authRoles.admin
            },
            {
                'id'   : 'product-categories-threshold',
                'title': 'Product Categories Threshold',
                'key'  : 'Product Category Threshold',
                'type' : 'item',
                'icon' : 'whatshot',
                'url'  : '/product/categories',
                'exact': true,
                'auth' : authRoles.admin,
            },
            {
                'id'   : 'running-maturity',
                'title': 'Running Maturity',
                'key'  : 'Runing Maturities',
                'type' : 'item',
                'icon' : 'whatshot',
                'url'  : '/running/maturity',
                'exact': true,
                'auth' : authRoles.admin,
            },
            {
                'id'   : 'department',
                'title': 'Departments',
                'key'  : 'Departments',
                'type' : 'item',
                'icon' : 'people',
                'url'  : '/apps/departments',
                'exact': true,
                'auth' : authRoles.admin,
            },
            {
                'id': 'pta-manager',
                'title': 'PTA Manager',
                'key': 'PTA Manager',
                'type': 'item',
                'icon': 'business',
                'url': '/apps/pta-manager',
                'exact': true,
                'auth' : authRoles.admin
            },
            {
                'id': 'branch-reorder',
                'title': 'Branch Re-Order Unit',
                'key': 'Branch Re-Order Unit',
                'type': 'item',
                'icon': 'business',
                'url': '/apps/branch',
                'exact': true,
                'auth' : authRoles.user,
            },
            {
                'id'   : 'all-rates',
                'title': 'Rates',
                'key'  : 'Exchange Rate',
                'type' : 'collapse',
                'icon' : 'assignment',
                'exact': true,
                'children': [
                    {
                        'id': 'currencies-rate',
                        'title': 'Currency Threshold',
                        'key': 'Exchange Rate',
                        'type': 'item',
                        'icon': 'money',
                        'url': '/rate/new',
                        'exact': true,
                        'auth' : authRoles.user,
                    },
                    {
                        'id'   : 'fx-switch',
                        'title': 'FX Rates Guide',
                        'key'  : 'TD Rate Guide',
                        'type' : 'item',
                        'icon' : 'money',
                        'url'  : '/rate/fxrates',
                        'exact': true,
                        'auth' : authRoles.user,
                    },
                    {
                        'id'   : 'fd-guide-rate',
                        'title': 'Fixed Deposit Rate',
                        'key'  : 'Fixed Deposit',
                        'type' : 'item',
                        'icon' : 'money',
                        'url'  : '/rate/deposits',
                        'exact': true,
                        'auth' : authRoles.user,
                    },
                ]
            }, 
            {
                'id'   : 'loan',
                'title': 'Loans',
                'key'  : 'Loans',
                'type' : 'collapse',
                'icon' : 'subject',
                'exact': true,
                'auth' : authRoles.admin,
                'children': [
                    {
                        'id'   : 'loan-exchange',
                        'title': 'Loan Exchange',
                        'key'  : 'Loans',
                        'type' : 'item',
                        'icon' : 'supervisor_account',
                        'url'  : '/loan/exchange',
                    },
                    {
                        'id'   : 'loan-report',
                        'title': 'Loan Report',
                        'key'  : 'Loans',
                        'type' : 'item',
                        'icon' : 'supervisor_account',
                        'url'  : '/loan/reports',
                    },
                ]
            },
            {
                'id'   : 'report',
                'title': 'Reports',
                'key'  : 'Reports',
                'type' : 'item',
                'icon' : 'subject',
                'url'  : '/apps/reports',
                'exact': true,
                'auth' : authRoles.user,
                'children': [
                    {
                        'id': 'reports-context',
                        'title': 'Reports',
                        'key': 'Reports',
                        'type': 'item',
                        'icon': 'subject',
                        'url': '/reports',
                        'auth' : authRoles.user,
                    },
                ]
            },
            {
                'id'   : 'roles',
                'title': 'Roles',
                'key'  : 'Roles',
                'type' : 'collapse',
                'icon' : 'supervisor_account',
                'exact': true,
                'auth' : authRoles.admin,
                'children': [
                    {
                        'id': 'admin-roles',
                        'title': 'Roles Management',
                        'key': 'Roles',
                        'type': 'item',
                        'icon': 'supervisor_account',
                        'url': '/role/new',
                    },
                    {
                        'id': 'admin-rights-mgt',
                        'title': 'Add Rights to Role',
                        'key'  : 'Roles',
                        'type': 'item',
                        'icon': 'supervisor_account',
                        'url': '/role/asign-rights',
                    },
                ]
            },
            {
                'id'   : 'admin-users',
                'title': 'Admin Users',
                'key'  : 'Admin Users',
                'type' : 'collapse',
                'icon' : 'supervisor_account',
                'auth' : authRoles.admin,
                'children': [
                    {
                        'id': 'new-admin',
                        'title': 'Create New Admin',
                        'key': 'Admin Users',
                        'type': 'item',
                        'icon': 'supervisor_account',
                        'url': '/admin/new',
                        'exact': true,
                        'auth' : authRoles.admin
                    },
                    {
                        'id'   : 'all-admin',
                        'title': 'Admin List',
                        'key'  : 'Admin Users',
                        'type' : 'item',
                        'icon' : 'supervisor_account',
                        'url'  : '/admin/accounts',
                        'exact': true,
                        'auth' : authRoles.admin
                    },
                    {
                        'id'   : 'rms',
                        'title': 'RM',
                        'key'  : 'Relation Manager',
                        'type' : 'item',
                        'icon' : 'chat',
                        'url'  : '/rms',
                        'exact': true,
                        'auth' : authRoles.admin
                    },
                    {
                        'id'   : 'customer-services',
                        'title': 'Customer Services',
                        'key'  : 'Customer Service',
                        'type' : 'item',
                        'icon' : 'chat',
                        'url'  : '/customer/services',
                        'exact': true,
                        'auth' : authRoles.admin
                    },
                ]
            },
            {
                'id'   : 'public-holiday',
                'title': 'Holiday Calendar',
                'key'  : 'Holiday Calendar',
                'type' : 'item',
                'icon' : 'calendar_today',
                'url'  : '/app/holiday-calendar',
                'auth' : authRoles.admin,
            },
            {
                'id'   : 'utilities',
                'title': 'Utility Settings',
                'key'  : 'Preferences',
                'type' : 'item',
                'icon' : 'calendar_today',
                'url'  : '/app/utilities',
                'auth' : authRoles.admin,
            },
            {
                'id'   : 'user-notification',
                'title': 'Notification',
                'key'  : 'Notifications',
                'type' : 'item',
                'icon' : 'calendar_today',
                'url'  : '/app/notification',
                'auth' : authRoles.admin,
            },
            {
                'id'   : 'branches',
                'title': 'Branches',
                'key'  : 'Branches',
                'type' : 'item',
                'icon' : 'ballot',
                'url'  : '/branches',
                'auth' : authRoles.admin,
            },
            {
                'id'   : 'pta-manager-doctype',
                'title': 'PTA Doc Type',
                'key'  : 'PTA Document Types',
                'type' : 'item',
                'icon' : 'note',
                'url'  : '/apps/ptadoctypes',
                'auth' : authRoles.admin
            },
            {
                'id'   : 'doctypes',
                'title': 'Document Types',
                'key'  : 'User Document Types',
                'type' : 'item',
                'icon' : 'note',
                'url'  : '/apps/doctypes',
                'auth' : authRoles.admin
            },
            {
                'id'   : 'user-preferences',
                'title': 'Registrations',
                'key'  : 'Registrations',
                'type' : 'item',
                'icon' : 'note',
                'url'  : '/tnc/reports',
                'auth' : authRoles.admin
            },
            {
                'id'   : 'terms-conditions',
                'title': 'Terms & Conditions',
                'key'  : 'Terms And Conditions',
                'type' : 'item',
                'icon' : 'note',
                'url'  : '/apps/tnc',
                'auth' : authRoles.admin
            },
            {
                'id'   : 'wallet-refund',
                'title': 'Fund Wallet',
                'key'  : 'Fund Wallet',
                'type' : 'item',
                'icon' : 'note',
                'url'  : '/apps/walletfund',
                'auth' : authRoles.admin
            },
            {
                'id': 'activity-logs',
                'title': 'Activity Logs',
                'key': 'Activity Log',
                'type': 'item',
                'icon': 'whatshot',
                'url': '/activity/logs',
                'exact': true,
                'auth' : authRoles.admin,
            },
        ]
    }
];

export default navigationConfig;
